# ----- ValidatingCLEO -----
# File: config.yaml
# Project: config
# Created Date: Thursday 20th March 2025
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Thursday 20th March 2025
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for 0D box model of collisions using CLEO.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "scripts/collisions/initconds.py" for usage) and likewise
# for "grid_filename".

### Initial Conditions Parameters for Python Script ###
python_initconds:
  paths:
    savefigpath: XXX
    sharepath: XXX
  supers:
    dryradius: 1.0e-16                                        # all SDs have negligible solute [m]
    volexpr0: XXX                                             # peak of volume exponential distribution [m]
    numconc: XXX                                              # = 2^23 = total no. conc of real droplets [m^-3]

### SDM Runtime Parameters ###
domain:
  nspacedims: 0                                               # no. of spatial dimensions to model
  ngbxs: 1                                                    # total number of Gbxs
  maxnsupers: XXX                                             # maximum number of SDs

timesteps:
  CONDTSTEP: 1                                                # time between SD condensation [s]
  COLLTSTEP: XXX                                              # time between SD collision [s]
  MOTIONTSTEP: 1                                              # time between SDM motion [s]
  COUPLTSTEP: 1200                                            # time between dynamic couplings [s]
  OBSTSTEP: 60                                                # time between SDM observations [s]
  T_END: XXX                                                  # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename: XXX                                       # name of file for values of physical constants
  grid_filename: XXX                                            # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename: XXX                                      # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename: XXX                                           # .txt filename to copy configuration to
  zarrbasedir: XXX                                              # zarr store base directory
  maxchunk: 2500000                                             # maximum no. of elements in chunks of zarr store array
