# ----- ValidatingCLEO -----
# File: config.yaml
# Project: config
# Created Date: Thursday 20th March 2025
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Thursday 20th March 2025
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for model of motion in a 2-D divergence free flow using CLEO.
# Note: The inital superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "scripts/motion/initconds.py" for usage) and likewise
# for "grid_filename".

### Initial Conditions Parameters for Python Script ###
python_initconds:
  paths:
    savefigpath: XXX
    sharepath: XXX
  grid:
    zgrid: [0, 1500, X]                                       # [max, min, spacing] of gridbox boundaries in z direction
    xgrid: [0, 1500, X]                                       # [max, min, spacing] of gridbox boundaries in x direction
    ygrid: [0, 10, 10]                                        # [max, min, spacing] of gridbox boundaries in y direction
  supers:
    nsupers_per_gbx: X                                        # number of superdroplets per gridbox
    mono_radius: 0.05e-6                                      # monodisperse droplet radii [m]
    numconc: 500.0e+6                                         # total no. conc of real droplets [m^-3]
  thermo:
    thermofiles: X                                            # names of thermofiles = thermofiles+"_[variable].dat"
    PRESS0: 101500                                            # surface pressure[Pa]
    THETA: 289                                                # potential temperature below Zbase [K]
    Zbase: 750                                                # height of cloud layer [m]
    qvapmethod: "qvap"                                        # calculate qvap from supersaturation ratios
    qvaps: [0.0075, 0.0075]                                   # supersaturation ratios [below, above] Zbase
    qcond_init: 0.0                                           # initial non-superdroplet qcond [Kg/Kg]
    WMAX: 0.6                                                 # maximum updraught velocity [m/s]
    Zlength: 1500                                             # divergent flow coord3 (z) lengthscale [m]
    Xlength: 1500                                             # divergent flow coord1 (x) lengthscale [m]

### SDM Runtime Parameters ###
domain:
  nspacedims: 2                                               # no. of spatial dimensions to model
  ngbxs: XXX                                                  # total number of Gbxs
  maxnsupers: XXX                                             # maximum number of SDs

timesteps:
  CONDTSTEP: 1                                                # time between SD condensation [s]
  COLLTSTEP: 1                                                # time between SD collision [s]
  MOTIONTSTEP: X                                              # time between SDM motion [s]
  COUPLTSTEP: 3600                                            # time between dynamic couplings [s]
  OBSTSTEP: X                                                 # time between SDM observations [s]
  T_END: 3600                                                 # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename: XXX                                       # name of file for values of physical constants
  grid_filename: XXX                                            # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename: XXX                                      # binary filename for initialisation of SDs

### Output Parameters ###
outputdata:
  setup_filename: XXX                                           # .txt filename to copy configuration to
  zarrbasedir: XXX                                              # zarr store base directory
  maxchunk: 2500000                                             # maximum no. of elements in chunks of zarr store array


### Coupled Dynamics Parameters ###
coupled_dynamics:
  type : fromfile                                         # type of coupled dynamics to configure
  press : XXX                                             # binary filename for pressure
  temp : XXX                                              # binary filename for temperature
  qvap : XXX                                              # binary filename for vapour mixing ratio
  qcond : XXX                                             # binary filename for liquid mixing ratio
  wvel : XXX                                              # binary filename for vertical (coord3) velocity
  uvel : XXX                                              # binary filename for eastwards (coord1) velocity
